// ── Publisher registry (Per App 30) ──
// The modular internal publishing layer flagged back at Per Bot 54 and
// scoped in PER_APP_30_CUTOVER.md. One entry point — publishToChannel()
// — that every route and cron job calls instead of talking to
// BulkPublish (or LinkedIn, or eventually Meta) directly. Adding a new
// channel or swapping a platform from BulkPublish to a direct
// integration is a one-line change to PLATFORM_PROVIDERS below —
// nothing in server.js's routes or the admin UI ever needs to change.
const bulkpublish = require('./bulkpublish');
const linkedin    = require('./linkedin');
const meta        = require('./meta');

// platform key (lowercase, matches what the admin UI already sends) ->
// provider module. Facebook/Instagram/Threads stay on BulkPublish until
// meta.js is actually built; flip these three to 'meta' then.
const PLATFORM_PROVIDERS = {
  linkedin:  'linkedin',
  facebook:  'bulkpublish',
  instagram: 'bulkpublish',
  threads:   'bulkpublish',
};

const PROVIDERS = { bulkpublish, linkedin, meta };

function providerFor(platform) {
  const key = PLATFORM_PROVIDERS[(platform || '').toLowerCase()];
  return key ? PROVIDERS[key] : null;
}

// Per App 31 — Facebook already auto-labels AI-generated images with
// its own badge (Per noticed this directly), and disclosure norms are
// only tightening across platforms, so an explicit line in the post
// text itself is worth having rather than relying solely on each
// platform's own detection. Every image/video Message Builder attaches
// is AI-generated by definition — there's no path anywhere in this app
// to attach a human-made one — so this applies whenever a post actually
// has media, no extra flag needed to say so.
function appendAiDisclosure(content, mediaType) {
  const label = mediaType === 'video' ? 'Video generated by AI.' : 'Image generated by AI.';
  const trimmed = (content || '').trimEnd();
  return trimmed ? `${trimmed}\n\n${label}` : label;
}

async function publishToChannel(platform, postData) {
  const provider = providerFor(platform);
  if (!provider) throw new Error(`No publishing provider is configured for "${platform}".`);
  // Applied here rather than at each call site (Message Builder's direct
  // publish, the scheduled queue, and the auto-prepare pipeline all call
  // this one function) so it can't be forgotten on any individual entry
  // point, present or future.
  const finalPostData = (postData && postData.mediaUrl)
    ? { ...postData, content: appendAiDisclosure(postData.content, postData.mediaType) }
    : postData;
  return provider.publish(platform, finalPostData);
}

// Merges every distinct provider's channel list into one flat array —
// used by the admin channels status route. Each provider is only ever
// called once even if several platforms map to it (e.g. BulkPublish
// covers three platforms but its /channels call already returns all of
// them at once).
async function listAllChannels() {
  const uniqueProviderKeys = [...new Set(Object.values(PLATFORM_PROVIDERS))];
  const results = await Promise.all(
    uniqueProviderKeys.map(key => PROVIDERS[key].listChannels().catch(() => []))
  );
  return results.flat();
}

module.exports = { publishToChannel, listAllChannels, providerFor, PLATFORM_PROVIDERS, PROVIDERS };
